steps:
  - id: 'build-image'
    name: 'gcr.io/distroless/java:8-debug'
    entrypoint: '/busybox/sh'
    args:
      - -c
      - |
        ln -s /busybox/env /usr/bin/env
        /workspace/gradlew --console=plain --no-daemon bootBuildImage --imageName=gcr.io/$PROJECT_ID/asdf

  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/asdf']

  - id: 'deploy'
    name: ghcr.io/jamesward/easycloudrun
    entrypoint: vpcsql
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_NAME=asdf'
      - 'REGION=us-central1'
      - 'DB_VERSION=POSTGRES_13'
      - 'DB_TIER=db-f1-micro'
      - 'DB_INIT_ARGS=init'

timeout: 20m
